// Pair finder: walk a project's git history for (generated, edited)
// commit pairs. A commit counts as generated when its Co-Authored-By
// trailer matches the agent pattern (the convention agent commits
// already carry) or, as a fallback, when its author name matches the
// agent-identity list. Its pairing "final" commit is the next commit by
// author date touching an overlapping path, with no agent marker.
//
// The author-name fallback used to be described here as safe because it
// "errs toward matching": a generated commit mistaken for a human one
// only loses that commit's signal. That reasoning was incomplete in the
// direction that costs more. A human commit mistaken for a generated one
// is not eligible as a pairing target, so it does not lose one commit's
// signal, it deletes the whole pair and the generated side with it.
//
// That asymmetry has a live trigger. Coding harnesses export
// GIT_AUTHOR_NAME, and those environment variables outrank a repository's
// own user.name, so in a project committed to from inside Claude Code or
// Cursor every commit in the history carries the harness's name. Both
// sides of every pair then match DEFAULT_AUTHOR, no commit is eligible as
// a final, and `ursa run` reports zero pairs on a repository full of real
// correction work. See the probe in m0.test.ts, "the ambient git identity".
//
// So the fallback is applied only when it discriminates. A pattern that
// matches every commit in a history is describing the environment the
// commits were made in rather than which of them were generated, and it
// is dropped in favour of the Co-Authored-By trailer, which does
// discriminate. The decision is reported in PairFinderDiagnostics rather
// than taken silently, because a suppressed fallback changes what a run
// finds and the user is owed that.

import { execFileSync } from 'node:child_process'

export interface CommitPair {
  generatedSha: string
  finalSha: string
  paths: string[]
  generatedAuthor: string
  finalAuthor: string
  generatedAt: string
  finalAt: string
  /** the trailer or author string that classified the generated side */
  agentMarker: string
  subject: string
}

export interface PairFinderOptions {
  agentTrailerPattern?: RegExp
  agentAuthorPattern?: RegExp
}

/** What a pair-finding walk decided, so a caller can explain an empty result. */
export interface PairFinderDiagnostics {
  /** commits reachable from any ref, the population the walk classified */
  commitsScanned: number
  /** commits classified generated by their Co-Authored-By trailer */
  generatedByTrailer: number
  /** commits classified generated by author name, after any suppression below */
  generatedByAuthorName: number
  /**
   * Set when the author-name pattern matched every commit in the history and
   * was therefore ignored. `authors` lists the distinct author names that
   * matched, which is what a caller should show the user, since that name is
   * the thing to change (or to override with agentAuthorPattern).
   */
  authorFallbackSuppressed: { pattern: string; authors: string[] } | null
}

const DEFAULT_TRAILER = /claude|codex|cursor|gpt/i
const DEFAULT_AUTHOR = /claude|codex|cursor|gpt|copilot|github-actions|\[bot\]/i

interface CommitInfo {
  sha: string
  authorName: string
  authorEmail: string
  date: string
  trailers: string
  subject: string
  /** more than one parent = a merge; a merge is never an edit */
  parentCount: number
}

function git(repoPath: string, args: string[]): string {
  return execFileSync('git', ['-C', repoPath, ...args], {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  })
}

export function listCommits(repoPath: string): CommitInfo[] {
  // --reverse with --topo-order: ancestors before descendants, so the
  // pairing scan walks forward in history even when commits share a
  // timestamp (same-second bursts are common in agent workflows).
  const out = git(repoPath, [
    'log', '--all', '--reverse', '--topo-order', '--date=iso-strict',
    '--pretty=format:%H%x09%an%x09%ae%x09%aI%x09%P%x09%(trailers:key=Co-Authored-By,valueonly,separator=|)%x09%s',
  ])
  return out.split('\n').filter(Boolean).map((line) => {
    const [sha, authorName, authorEmail, date, parents, trailers, ...rest] = line.split('\t')
    return {
      sha, authorName, authorEmail, date,
      parentCount: parents ? parents.split(' ').length : 0,
      trailers: trailers ?? '',
      subject: rest.join('\t'),
    }
  })
}

export function commitFiles(repoPath: string, sha: string): string[] {
  return git(repoPath, ['show', '--name-only', "--format=", sha])
    .split('\n').filter(Boolean)
}

export function blobAt(repoPath: string, sha: string, path: string): string | null {
  try {
    return git(repoPath, ['show', `${sha}:${path}`])
  } catch {
    return null
  }
}

/** The pairs alone. Unchanged signature, for callers that do not report. */
export function findCommitPairs(repoPath: string, opts: PairFinderOptions = {}): CommitPair[] {
  return findCommitPairsWithDiagnostics(repoPath, opts).pairs
}

export function findCommitPairsWithDiagnostics(
  repoPath: string,
  opts: PairFinderOptions = {},
): { pairs: CommitPair[]; diagnostics: PairFinderDiagnostics } {
  const trailerPattern = opts.agentTrailerPattern ?? DEFAULT_TRAILER
  const authorPattern = opts.agentAuthorPattern ?? DEFAULT_AUTHOR
  const commits = listCommits(repoPath)
  const files = new Map<string, string[]>()
  const touched = (sha: string) => {
    if (!files.has(sha)) files.set(sha, commitFiles(repoPath, sha))
    return files.get(sha)!
  }

  // Does the author pattern separate this history, or just label all of it?
  // Two commits is the floor: below it no pair can exist, so suppressing
  // would change no result and the notice would only mislead.
  const authorMatchesAll =
    commits.length >= 2 && commits.every((c) => authorPattern.test(c.authorName))
  const useAuthorFallback = !authorMatchesAll
  const diagnostics: PairFinderDiagnostics = {
    commitsScanned: commits.length,
    generatedByTrailer: 0,
    generatedByAuthorName: 0,
    authorFallbackSuppressed: authorMatchesAll
      ? {
          pattern: String(authorPattern),
          authors: [...new Set(commits.map((c) => c.authorName))].sort(),
        }
      : null,
  }

  const marker = (c: CommitInfo): string | null => {
    if (trailerPattern.test(c.trailers)) return c.trailers
    if (useAuthorFallback && authorPattern.test(c.authorName)) return c.authorName
    return null
  }

  for (const c of commits) {
    if (trailerPattern.test(c.trailers)) diagnostics.generatedByTrailer += 1
    else if (useAuthorFallback && authorPattern.test(c.authorName)) {
      diagnostics.generatedByAuthorName += 1
    }
  }

  const pairs: CommitPair[] = []
  for (let i = 0; i < commits.length; i++) {
    const gen = commits[i]
    const agentMarker = marker(gen)
    if (!agentMarker) continue
    const genFiles = new Set(touched(gen.sha))
    if (genFiles.size === 0) continue
    for (let j = i + 1; j < commits.length; j++) {
      const fin = commits[j]
      if (marker(fin)) continue
      // A merge brings in other commits' work; the human did not write
      // that diff. Skip it as a pairing target rather than count another
      // agent's changes as this person's corrections.
      if (fin.parentCount > 1) continue
      const overlap = touched(fin.sha).filter((p) => genFiles.has(p))
      if (overlap.length === 0) continue
      pairs.push({
        generatedSha: gen.sha,
        finalSha: fin.sha,
        paths: overlap,
        generatedAuthor: gen.authorName,
        finalAuthor: fin.authorName,
        generatedAt: gen.date,
        finalAt: fin.date,
        agentMarker,
        subject: gen.subject,
      })
      break
    }
  }
  return { pairs, diagnostics }
}
