// Pair finder: walk a project's git history for (generated, edited)
// commit pairs. A commit counts as generated when its Co-Authored-By
// trailer matches the agent pattern (the convention agent commits
// already carry) or, as a fallback, when its author name matches the
// agent-identity list. Its pairing "final" commit is the next commit by
// author date touching an overlapping path, with no agent marker. Merges
// and other agents' commits between the two are skipped as pairing
// targets but not forgotten: a merge between them can destroy the
// generation's text without any human choosing to drop it, so each
// skipped merge that touched a paired path is reported on the pair as an
// `interveningMerges` entry for deletion attribution to read.
//
// The author-name fallback used to be described here as safe because it
// "errs toward matching": a generated commit mistaken for a human one
// only loses that commit's signal. That reasoning was incomplete in the
// direction that costs more. A human commit mistaken for a generated one
// is not eligible as a pairing target, so it does not lose one commit's
// signal, it deletes the whole pair and the generated side with it.
//
// That asymmetry has a live trigger. Coding harnesses export
// GIT_AUTHOR_NAME, and those environment variables outrank a repository's
// own user.name, so in a project committed to from inside Claude Code or
// Cursor every commit in the history carries the harness's name. Both
// sides of every pair then match DEFAULT_AUTHOR, no commit is eligible as
// a final, and `ursa run` reports zero pairs on a repository full of real
// correction work. See the probe in m0.test.ts, "the ambient git identity".
//
// So the fallback is applied only when it discriminates. A pattern that
// matches every commit in a history is describing the environment the
// commits were made in rather than which of them were generated, and it
// is dropped in favour of the Co-Authored-By trailer, which does
// discriminate. The decision is reported in PairFinderDiagnostics rather
// than taken silently, because a suppressed fallback changes what a run
// finds and the user is owed that.

import { execFileSync } from 'node:child_process'

/** a merge commit sitting between the generated and final commit */
export interface MergeEvent {
  sha: string
  /** the merge's parents, in git's order; parents[0] is the first parent */
  parents: string[]
  /** paths this merge touched that the generation also touched */
  paths: string[]
  author: string
  date: string
  subject: string
}

export interface CommitPair {
  generatedSha: string
  finalSha: string
  paths: string[]
  generatedAuthor: string
  finalAuthor: string
  generatedAt: string
  finalAt: string
  /** the trailer or author string that classified the generated side */
  agentMarker: string
  subject: string
  /**
   * Merges walked past on the way from generatedSha to finalSha that
   * touched at least one of the generation's paths, oldest first. Text
   * these destroyed is not the human's discard.
   */
  interveningMerges: MergeEvent[]
}

export interface PairFinderOptions {
  agentTrailerPattern?: RegExp
  agentAuthorPattern?: RegExp
  /**
   * Commits walked forward from a generation before the pair claim is
   * abandoned. A generation and an edit 42 commits apart are not a
   * correction loop, they are two unrelated visits to the same file.
   */
  maxPairDistance?: number
  /**
   * Hours between the generation's author date and the edit's before the
   * pair claim is abandoned. Separate from distance because a dense
   * same-session burst and a sparse ten-day history look identical by
   * commit count and nothing alike as correction work.
   */
  maxPairAgeHours?: number
  /**
   * How many OTHER generations may rewrite one of this generation's own
   * paths before the pair claim is abandoned. Zero is the default and the
   * honest value: if another generation rewrote the file first, the human's
   * commit is a correction of that one, and this generation's text was
   * never the thing in front of them.
   */
  maxInterposedGenerations?: number
}

/** What a pair-finding walk decided, so a caller can explain an empty result. */
export interface PairFinderDiagnostics {
  /** commits reachable from any ref, the population the walk classified */
  commitsScanned: number
  /** commits classified generated by their Co-Authored-By trailer */
  generatedByTrailer: number
  /** commits classified generated by author name, after any suppression below */
  generatedByAuthorName: number
  /**
   * Set when the author-name pattern matched every commit in the history and
   * was therefore ignored. `authors` lists the distinct author names that
   * matched, which is what a caller should show the user, since that name is
   * the thing to change (or to override with agentAuthorPattern).
   */
  authorFallbackSuppressed: { pattern: string; authors: string[] } | null
  /** the bounds this walk ran under, so a caller can name them to the user */
  bounds: {
    maxPairDistance: number
    maxPairAgeHours: number
    maxInterposedGenerations: number
  }
  /**
   * Generations that found no edit because the walk hit a bound, counted by
   * whichever bound stopped it FIRST. A generation appears at most once
   * here, and never here if it produced a pair.
   */
  abandoned: {
    distance: number
    age: number
    interposedGeneration: number
    /** the only edit found was on a branch the generation is not an ancestor of */
    notDescendant: number
  }
  /**
   * Commits that carried an agent marker, were merges, and were therefore
   * refused as generations. A merge's diff is other commits' work; it
   * generated nothing of its own.
   */
  mergeGenerationsRefused: number
}

const DEFAULT_TRAILER = /claude|codex|cursor|gpt/i
/**
 * The pairing bounds' defaults, with the reasoning that chose each number
 * rather than a round figure.
 *
 * 25 commits: measured on this repository's own `main` at 0d68df0 (98
 * commits), where the unbounded walk produced six pairs whose generated
 * sides sat 1, 4, 9, 37, 39 and 42 commits from the single edit all six
 * claimed. The three far pairs are the ones that credit a generation with
 * a file it did not write. 25 sits above every pair a reviewer would call
 * real here and below all three of those.
 *
 * 168 hours (7 days): the same six pairs spanned 30.6, 48.4, 97.0, 217.1,
 * 223.2 and 234.6 hours. A correction arriving after a working week is not
 * a correction loop; it is a later visit to the same file.
 *
 * 0 interposed generations: not a tuning parameter. One other generation
 * rewriting the path is enough to mean the human never had this
 * generation's text in front of them.
 */
const DEFAULT_MAX_PAIR_DISTANCE = 25
const DEFAULT_MAX_PAIR_AGE_HOURS = 168
const DEFAULT_MAX_INTERPOSED_GENERATIONS = 0
const DEFAULT_AUTHOR = /claude|codex|cursor|gpt|copilot|github-actions|\[bot\]/i

interface CommitInfo {
  sha: string
  authorName: string
  authorEmail: string
  date: string
  trailers: string
  subject: string
  /** parent shas in git's order; length > 1 = a merge, and a merge is never an edit */
  parents: string[]
}

function git(repoPath: string, args: string[], opts: { quiet?: boolean } = {}): string {
  return execFileSync('git', ['-C', repoPath, ...args], {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
    // `quiet` drops git's stderr. Used by the blob and commit-presence
    // probes, because a missing path or a missing commit at a given sha is
    // an expected answer there (deploy detection probes for files that may
    // not exist), not a failure worth printing.
    stdio: opts.quiet ? ['ignore', 'pipe', 'ignore'] : undefined,
  })
}

export function listCommits(repoPath: string): CommitInfo[] {
  // --reverse with --topo-order: ancestors before descendants, so the
  // pairing scan walks forward in history even when commits share a
  // timestamp (same-second bursts are common in agent workflows).
  const out = git(repoPath, [
    'log', '--all', '--reverse', '--topo-order', '--date=iso-strict',
    '--pretty=format:%H%x09%an%x09%ae%x09%aI%x09%P%x09%(trailers:key=Co-Authored-By,valueonly,separator=|)%x09%s',
  ])
  return out.split('\n').filter(Boolean).map((line) => {
    const [sha, authorName, authorEmail, date, parents, trailers, ...rest] = line.split('\t')
    return {
      sha, authorName, authorEmail, date,
      parents: parents ? parents.split(' ').filter(Boolean) : [],
      trailers: trailers ?? '',
      subject: rest.join('\t'),
    }
  })
}

/**
 * Paths a commit touched, including merges.
 *
 * `-m` is load-bearing: without it `git show --name-only` prints NOTHING
 * for a merge commit, because git shows no diff for a merge by default.
 * That blindness is why `findCommitPairs` appeared to refuse merges as
 * pairing targets even before the explicit parent check — a merge simply
 * never reported an overlapping path. With `-m` git diffs the merge
 * against each parent in turn, so a path is listed once per parent that
 * differs; dedupe, since callers only ask whether the path was touched.
 */
export function commitFiles(repoPath: string, sha: string): string[] {
  const out = git(repoPath, ['show', '-m', '--name-only', "--format=", sha])
  return [...new Set(out.split('\n').filter(Boolean))]
}

/**
 * Three-state blob read, for callers that have to tell "the text is not
 * there" from "this repository cannot say".
 *
 * `git show <sha>:<path>` fails for two reasons that mean opposite
 * things. Either the commit is right here and the path is simply not in
 * its tree, which is a definite answer, or something the answer needs is
 * missing from this clone — the commit itself after a shallow fetch, the
 * blob in a `--filter=blob:none` clone whose promisor is unreachable —
 * which is no answer at all. `blobAt` collapses both to `null`, and the
 * collapse is what let deletion attribution charge an unreadable
 * boundary to the person (see src/deletion.ts).
 *
 * The discriminator is `git ls-tree <sha> -- <path>`, run only on the
 * failure path so the common case still costs one process. It reads the
 * commit's tree objects and nothing else, which gives all three answers
 * from one call:
 *
 *   - the command fails          the commit or its trees are not here
 *   - it succeeds, prints nothing the path is genuinely not in this tree
 *   - it succeeds, prints a row   the path is there and the blob itself
 *                                 could not be read
 *
 * The third row is why this is `ls-tree` rather than
 * `cat-file -e <sha>^{commit}`: a partial clone holds every commit and
 * tree while the blob lives on a remote, so a commit-presence probe
 * reports a definite "not in the tree" for a file that is in the tree.
 */
export type BlobLookup =
  | { kind: 'present'; text: string }
  | { kind: 'absent' }
  | { kind: 'unreadable' }

export function blobLookup(repoPath: string, sha: string, path: string): BlobLookup {
  try {
    return { kind: 'present', text: git(repoPath, ['show', `${sha}:${path}`], { quiet: true }) }
  } catch {
    let listed: string
    try {
      listed = git(repoPath, ['ls-tree', sha, '--', path], { quiet: true })
    } catch {
      return { kind: 'unreadable' }
    }
    return listed.trim() === '' ? { kind: 'absent' } : { kind: 'unreadable' }
  }
}

/**
 * The two-state read. Kept for callers that probe for a file they do not
 * expect to exist (deploy detection, lifespan sampling), where absent and
 * unreadable both correctly mean "no text to read".
 */
export function blobAt(repoPath: string, sha: string, path: string): string | null {
  const got = blobLookup(repoPath, sha, path)
  return got.kind === 'present' ? got.text : null
}

/**
 * Is `ancestor` reachable from `descendant` by walking parents?
 *
 * `git merge-base --is-ancestor` answers with an exit code: 0 yes, 1 no.
 * A commit is its own ancestor by git's definition, which is the
 * convention this wrapper keeps.
 *
 * Pairing needs this because "between" in a git history is a question
 * about the graph and not about a list. The pair walk reads commits in
 * `--topo-order`, which linearises branches that never touched each
 * other, so a commit printed between two others may sit on a sibling
 * branch and have had no part in what happened to them. See the
 * interposition test in `findCommitPairsWithDiagnostics`, which is wrong
 * in both directions without it: it drops a real pair when a rival
 * branch's generation is mistaken for an interposed one, and keeps a
 * false pair when an edit on another branch is mistaken for a
 * correction of this generation.
 */
export function isAncestor(repoPath: string, ancestor: string, descendant: string): boolean {
  if (ancestor === descendant) return true
  try {
    git(repoPath, ['merge-base', '--is-ancestor', ancestor, descendant], { quiet: true })
    return true
  } catch {
    return false
  }
}

/** The pairs alone. Unchanged signature, for callers that do not report. */
export function findCommitPairs(repoPath: string, opts: PairFinderOptions = {}): CommitPair[] {
  return findCommitPairsWithDiagnostics(repoPath, opts).pairs
}

export function findCommitPairsWithDiagnostics(
  repoPath: string,
  opts: PairFinderOptions = {},
): { pairs: CommitPair[]; diagnostics: PairFinderDiagnostics } {
  const trailerPattern = opts.agentTrailerPattern ?? DEFAULT_TRAILER
  const authorPattern = opts.agentAuthorPattern ?? DEFAULT_AUTHOR
  const maxDistance = opts.maxPairDistance ?? DEFAULT_MAX_PAIR_DISTANCE
  const maxAgeHours = opts.maxPairAgeHours ?? DEFAULT_MAX_PAIR_AGE_HOURS
  const maxInterposed = opts.maxInterposedGenerations ?? DEFAULT_MAX_INTERPOSED_GENERATIONS
  const commits = listCommits(repoPath)
  const files = new Map<string, string[]>()
  const touched = (sha: string) => {
    if (!files.has(sha)) files.set(sha, commitFiles(repoPath, sha))
    return files.get(sha)!
  }

  // Does the author pattern separate this history, or just label all of it?
  // Two commits is the floor: below it no pair can exist, so suppressing
  // would change no result and the notice would only mislead.
  const authorMatchesAll =
    commits.length >= 2 && commits.every((c) => authorPattern.test(c.authorName))
  const useAuthorFallback = !authorMatchesAll
  const diagnostics: PairFinderDiagnostics = {
    commitsScanned: commits.length,
    generatedByTrailer: 0,
    generatedByAuthorName: 0,
    authorFallbackSuppressed: authorMatchesAll
      ? {
          pattern: String(authorPattern),
          authors: [...new Set(commits.map((c) => c.authorName))].sort(),
        }
      : null,
    bounds: {
      maxPairDistance: maxDistance,
      maxPairAgeHours: maxAgeHours,
      maxInterposedGenerations: maxInterposed,
    },
    abandoned: { distance: 0, age: 0, interposedGeneration: 0, notDescendant: 0 },
    mergeGenerationsRefused: 0,
  }

  const marker = (c: CommitInfo): string | null => {
    if (trailerPattern.test(c.trailers)) return c.trailers
    if (useAuthorFallback && authorPattern.test(c.authorName)) return c.authorName
    return null
  }

  for (const c of commits) {
    if (trailerPattern.test(c.trailers)) diagnostics.generatedByTrailer += 1
    else if (useAuthorFallback && authorPattern.test(c.authorName)) {
      diagnostics.generatedByAuthorName += 1
    }
  }

  const hoursBetween = (from: string, to: string) =>
    (Date.parse(to) - Date.parse(from)) / 3_600_000

  const ancestry = new Map<string, boolean>()
  const descends = (ancestor: string, descendant: string) => {
    const key = `${ancestor}..${descendant}`
    if (!ancestry.has(key)) ancestry.set(key, isAncestor(repoPath, ancestor, descendant))
    return ancestry.get(key)!
  }

  const pairs: CommitPair[] = []
  for (let i = 0; i < commits.length; i++) {
    const gen = commits[i]
    const agentMarker = marker(gen)
    if (!agentMarker) continue
    // A merge is not a generation, for the same reason it is not an edit:
    // its diff against a parent is other commits' work, restated. Before
    // this guard a merge authored by the harness identity matched the
    // author fallback, became a generation, and claimed the whole file at
    // the merge point as text it had produced. Two of the six pairs this
    // repository's own history produced were merges.
    if (gen.parents.length > 1) {
      diagnostics.mergeGenerationsRefused += 1
      continue
    }
    const genFiles = new Set(touched(gen.sha))
    if (genFiles.size === 0) continue
    const interveningMerges: MergeEvent[] = []
    for (let j = i + 1; j < commits.length; j++) {
      const fin = commits[j]
      // The distance bound stops the walk, which is also what keeps it
      // cheap: without it a generation in a long all-agent stretch walks
      // to the end of history. Position in this list is monotonic, so
      // breaking at the first commit past the bound is safe.
      //
      // The age bound is NOT checked here, and the reason is worth
      // stating. Author dates are not monotonic in --topo-order: a
      // rebased commit carries an old date, and a long-lived branch
      // merged in carries a much later one than the commits that follow
      // it. Testing every commit walked made a single oddly-dated commit
      // in the middle abandon the generation, which a fixture caught
      // immediately. The bound is a claim about the generation and the
      // edit, so it is checked against the edit, below.
      if (j - i > maxDistance) { diagnostics.abandoned.distance += 1; break }
      // A merge brings in other commits' work; the human did not write
      // that diff. It is not a pairing target. But it can still have
      // destroyed this generation's text, so record it before moving on
      // and let deletion attribution decide whose deletion it was.
      //
      // This test runs BEFORE the agent-marker test, and the order is the
      // whole point. A merge authored by a harness identity, or carrying a
      // Co-Authored-By trailer in its message, matches `marker` and used to
      // be skipped by it, so it was never recorded here — and deletion
      // attribution, finding no intervening merge, charged the merge's
      // destruction to the person. That is the defect src/deletion.ts was
      // built to prevent, re-entering one level up through classification
      // order.
      if (fin.parents.length > 1) {
        const mergeOverlap = touched(fin.sha).filter((p) => genFiles.has(p))
        if (mergeOverlap.length > 0) {
          interveningMerges.push({
            sha: fin.sha,
            parents: fin.parents,
            paths: mergeOverlap,
            author: fin.authorName,
            date: fin.date,
            subject: fin.subject,
          })
        }
        continue
      }
      if (marker(fin)) continue
      const overlap = touched(fin.sha).filter((p) => genFiles.has(p))
      if (overlap.length === 0) continue
      // From here `fin` is a candidate, and the remaining tests are about
      // this pair rather than about the walk.
      if (hoursBetween(gen.date, fin.date) > maxAgeHours) {
        diagnostics.abandoned.age += 1
        break
      }
      // The next two are about the shape of the graph rather than the
      // order of the list.
      //
      // First: the edit has to descend from the generation. An edit on a
      // branch that never contained this generation's text cannot be a
      // correction of it, however close it prints in --topo-order.
      if (!descends(gen.sha, fin.sha)) {
        diagnostics.abandoned.notDescendant += 1
        break
      }
      // Second: no OTHER generation may sit on the path from the
      // generation to the edit. "On the path" is the load-bearing phrase.
      // A rival branch's generation that a merge later brought in is not
      // on it — the merge is the mechanism there, it is already recorded
      // in interveningMerges, and src/deletion.ts attributes the loss to
      // it. What this test excludes is the straight-line case: the agent
      // rewrote the same file again, so the text the human had in front
      // of them at `fin` is that later generation's, and crediting this
      // one with surviving it is the defect.
      const interposed = commits.slice(i + 1, j).filter(
        (c) =>
          c.parents.length === 1 &&
          marker(c) &&
          touched(c.sha).some((p) => genFiles.has(p)) &&
          descends(gen.sha, c.sha) &&
          descends(c.sha, fin.sha),
      )
      if (interposed.length > maxInterposed) {
        diagnostics.abandoned.interposedGeneration += 1
        break
      }
      pairs.push({
        generatedSha: gen.sha,
        finalSha: fin.sha,
        paths: overlap,
        generatedAuthor: gen.authorName,
        finalAuthor: fin.authorName,
        generatedAt: gen.date,
        finalAt: fin.date,
        agentMarker,
        subject: gen.subject,
        interveningMerges,
      })
      break
    }
  }
  return { pairs, diagnostics }
}
