// Pair finder: walk a project's git history for (generated, edited)
// commit pairs. A commit counts as generated when its Co-Authored-By
// trailer matches the agent pattern (the convention agent commits
// already carry) or, as a fallback, when its author name matches the
// agent-identity list. Its pairing "final" commit is the next commit by
// author date touching an overlapping path, with no agent marker. Merges
// and other agents' commits between the two are skipped as pairing
// targets but not forgotten: a merge between them can destroy the
// generation's text without any human choosing to drop it, so each
// skipped merge that touched a paired path is reported on the pair as an
// `interveningMerges` entry for deletion attribution to read.
//
// The author-name fallback used to be described here as safe because it
// "errs toward matching": a generated commit mistaken for a human one
// only loses that commit's signal. That reasoning was incomplete in the
// direction that costs more. A human commit mistaken for a generated one
// is not eligible as a pairing target, so it does not lose one commit's
// signal, it deletes the whole pair and the generated side with it.
//
// That asymmetry has a live trigger. Coding harnesses export
// GIT_AUTHOR_NAME, and those environment variables outrank a repository's
// own user.name, so in a project committed to from inside Claude Code or
// Cursor every commit in the history carries the harness's name. Both
// sides of every pair then match DEFAULT_AUTHOR, no commit is eligible as
// a final, and `ursa run` reports zero pairs on a repository full of real
// correction work. See the probe in m0.test.ts, "the ambient git identity".
//
// So the fallback is applied only when it discriminates. A pattern that
// matches every commit in a history is describing the environment the
// commits were made in rather than which of them were generated, and it
// is dropped in favour of the Co-Authored-By trailer, which does
// discriminate. The decision is reported in PairFinderDiagnostics rather
// than taken silently, because a suppressed fallback changes what a run
// finds and the user is owed that.

import { execFileSync } from 'node:child_process'

/** a merge commit sitting between the generated and final commit */
export interface MergeEvent {
  sha: string
  /** the merge's parents, in git's order; parents[0] is the first parent */
  parents: string[]
  /** paths this merge touched that the generation also touched */
  paths: string[]
  author: string
  date: string
  subject: string
}

export interface CommitPair {
  generatedSha: string
  finalSha: string
  paths: string[]
  generatedAuthor: string
  finalAuthor: string
  generatedAt: string
  finalAt: string
  /** the trailer or author string that classified the generated side */
  agentMarker: string
  subject: string
  /**
   * Merges walked past on the way from generatedSha to finalSha that
   * touched at least one of the generation's paths, oldest first. Text
   * these destroyed is not the human's discard.
   */
  interveningMerges: MergeEvent[]
}

export interface PairFinderOptions {
  agentTrailerPattern?: RegExp
  agentAuthorPattern?: RegExp
}

/** What a pair-finding walk decided, so a caller can explain an empty result. */
export interface PairFinderDiagnostics {
  /** commits reachable from any ref, the population the walk classified */
  commitsScanned: number
  /** commits classified generated by their Co-Authored-By trailer */
  generatedByTrailer: number
  /** commits classified generated by author name, after any suppression below */
  generatedByAuthorName: number
  /**
   * Set when the author-name pattern matched every commit in the history and
   * was therefore ignored. `authors` lists the distinct author names that
   * matched, which is what a caller should show the user, since that name is
   * the thing to change (or to override with agentAuthorPattern).
   */
  authorFallbackSuppressed: { pattern: string; authors: string[] } | null
}

const DEFAULT_TRAILER = /claude|codex|cursor|gpt/i
const DEFAULT_AUTHOR = /claude|codex|cursor|gpt|copilot|github-actions|\[bot\]/i

interface CommitInfo {
  sha: string
  authorName: string
  authorEmail: string
  date: string
  trailers: string
  subject: string
  /** parent shas in git's order; length > 1 = a merge, and a merge is never an edit */
  parents: string[]
}

function git(repoPath: string, args: string[], opts: { quiet?: boolean } = {}): string {
  return execFileSync('git', ['-C', repoPath, ...args], {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
    // `quiet` drops git's stderr. Used by the blob and commit-presence
    // probes, because a missing path or a missing commit at a given sha is
    // an expected answer there (deploy detection probes for files that may
    // not exist), not a failure worth printing.
    stdio: opts.quiet ? ['ignore', 'pipe', 'ignore'] : undefined,
  })
}

export function listCommits(repoPath: string): CommitInfo[] {
  // --reverse with --topo-order: ancestors before descendants, so the
  // pairing scan walks forward in history even when commits share a
  // timestamp (same-second bursts are common in agent workflows).
  const out = git(repoPath, [
    'log', '--all', '--reverse', '--topo-order', '--date=iso-strict',
    '--pretty=format:%H%x09%an%x09%ae%x09%aI%x09%P%x09%(trailers:key=Co-Authored-By,valueonly,separator=|)%x09%s',
  ])
  return out.split('\n').filter(Boolean).map((line) => {
    const [sha, authorName, authorEmail, date, parents, trailers, ...rest] = line.split('\t')
    return {
      sha, authorName, authorEmail, date,
      parents: parents ? parents.split(' ').filter(Boolean) : [],
      trailers: trailers ?? '',
      subject: rest.join('\t'),
    }
  })
}

/**
 * Paths a commit touched, including merges.
 *
 * `-m` is load-bearing: without it `git show --name-only` prints NOTHING
 * for a merge commit, because git shows no diff for a merge by default.
 * That blindness is why `findCommitPairs` appeared to refuse merges as
 * pairing targets even before the explicit parent check — a merge simply
 * never reported an overlapping path. With `-m` git diffs the merge
 * against each parent in turn, so a path is listed once per parent that
 * differs; dedupe, since callers only ask whether the path was touched.
 */
export function commitFiles(repoPath: string, sha: string): string[] {
  const out = git(repoPath, ['show', '-m', '--name-only', "--format=", sha])
  return [...new Set(out.split('\n').filter(Boolean))]
}

/**
 * Three-state blob read, for callers that have to tell "the text is not
 * there" from "this repository cannot say".
 *
 * `git show <sha>:<path>` fails for two reasons that mean opposite
 * things. Either the commit is right here and the path is simply not in
 * its tree, which is a definite answer, or something the answer needs is
 * missing from this clone — the commit itself after a shallow fetch, the
 * blob in a `--filter=blob:none` clone whose promisor is unreachable —
 * which is no answer at all. `blobAt` collapses both to `null`, and the
 * collapse is what let deletion attribution charge an unreadable
 * boundary to the person (see src/deletion.ts).
 *
 * The discriminator is `git ls-tree <sha> -- <path>`, run only on the
 * failure path so the common case still costs one process. It reads the
 * commit's tree objects and nothing else, which gives all three answers
 * from one call:
 *
 *   - the command fails          the commit or its trees are not here
 *   - it succeeds, prints nothing the path is genuinely not in this tree
 *   - it succeeds, prints a row   the path is there and the blob itself
 *                                 could not be read
 *
 * The third row is why this is `ls-tree` rather than
 * `cat-file -e <sha>^{commit}`: a partial clone holds every commit and
 * tree while the blob lives on a remote, so a commit-presence probe
 * reports a definite "not in the tree" for a file that is in the tree.
 */
export type BlobLookup =
  | { kind: 'present'; text: string }
  | { kind: 'absent' }
  | { kind: 'unreadable' }

export function blobLookup(repoPath: string, sha: string, path: string): BlobLookup {
  try {
    return { kind: 'present', text: git(repoPath, ['show', `${sha}:${path}`], { quiet: true }) }
  } catch {
    let listed: string
    try {
      listed = git(repoPath, ['ls-tree', sha, '--', path], { quiet: true })
    } catch {
      return { kind: 'unreadable' }
    }
    return listed.trim() === '' ? { kind: 'absent' } : { kind: 'unreadable' }
  }
}

/**
 * The two-state read. Kept for callers that probe for a file they do not
 * expect to exist (deploy detection, lifespan sampling), where absent and
 * unreadable both correctly mean "no text to read".
 */
export function blobAt(repoPath: string, sha: string, path: string): string | null {
  const got = blobLookup(repoPath, sha, path)
  return got.kind === 'present' ? got.text : null
}

/** The pairs alone. Unchanged signature, for callers that do not report. */
export function findCommitPairs(repoPath: string, opts: PairFinderOptions = {}): CommitPair[] {
  return findCommitPairsWithDiagnostics(repoPath, opts).pairs
}

export function findCommitPairsWithDiagnostics(
  repoPath: string,
  opts: PairFinderOptions = {},
): { pairs: CommitPair[]; diagnostics: PairFinderDiagnostics } {
  const trailerPattern = opts.agentTrailerPattern ?? DEFAULT_TRAILER
  const authorPattern = opts.agentAuthorPattern ?? DEFAULT_AUTHOR
  const commits = listCommits(repoPath)
  const files = new Map<string, string[]>()
  const touched = (sha: string) => {
    if (!files.has(sha)) files.set(sha, commitFiles(repoPath, sha))
    return files.get(sha)!
  }

  // Does the author pattern separate this history, or just label all of it?
  // Two commits is the floor: below it no pair can exist, so suppressing
  // would change no result and the notice would only mislead.
  const authorMatchesAll =
    commits.length >= 2 && commits.every((c) => authorPattern.test(c.authorName))
  const useAuthorFallback = !authorMatchesAll
  const diagnostics: PairFinderDiagnostics = {
    commitsScanned: commits.length,
    generatedByTrailer: 0,
    generatedByAuthorName: 0,
    authorFallbackSuppressed: authorMatchesAll
      ? {
          pattern: String(authorPattern),
          authors: [...new Set(commits.map((c) => c.authorName))].sort(),
        }
      : null,
  }

  const marker = (c: CommitInfo): string | null => {
    if (trailerPattern.test(c.trailers)) return c.trailers
    if (useAuthorFallback && authorPattern.test(c.authorName)) return c.authorName
    return null
  }

  for (const c of commits) {
    if (trailerPattern.test(c.trailers)) diagnostics.generatedByTrailer += 1
    else if (useAuthorFallback && authorPattern.test(c.authorName)) {
      diagnostics.generatedByAuthorName += 1
    }
  }

  const pairs: CommitPair[] = []
  for (let i = 0; i < commits.length; i++) {
    const gen = commits[i]
    const agentMarker = marker(gen)
    if (!agentMarker) continue
    const genFiles = new Set(touched(gen.sha))
    if (genFiles.size === 0) continue
    const interveningMerges: MergeEvent[] = []
    for (let j = i + 1; j < commits.length; j++) {
      const fin = commits[j]
      if (marker(fin)) continue
      // A merge brings in other commits' work; the human did not write
      // that diff. It is not a pairing target. But it can still have
      // destroyed this generation's text, so record it before moving on
      // and let deletion attribution decide whose deletion it was.
      if (fin.parents.length > 1) {
        const mergeOverlap = touched(fin.sha).filter((p) => genFiles.has(p))
        if (mergeOverlap.length > 0) {
          interveningMerges.push({
            sha: fin.sha,
            parents: fin.parents,
            paths: mergeOverlap,
            author: fin.authorName,
            date: fin.date,
            subject: fin.subject,
          })
        }
        continue
      }
      const overlap = touched(fin.sha).filter((p) => genFiles.has(p))
      if (overlap.length === 0) continue
      pairs.push({
        generatedSha: gen.sha,
        finalSha: fin.sha,
        paths: overlap,
        generatedAuthor: gen.authorName,
        finalAuthor: fin.authorName,
        generatedAt: gen.date,
        finalAt: fin.date,
        agentMarker,
        subject: gen.subject,
        interveningMerges,
      })
      break
    }
  }
  return { pairs, diagnostics }
}
