// Records real MiniLM output for the fixture store into vectors.json, so
// the semantic ranking tests can assert on real embeddings without the
// optional 831MB dependency and a 23MB model download in CI.
//
//   npx tsx src/hq/record-vectors.ts
//
// The alternative designs, and why this one:
//
//   - Hand-written vectors would test the arithmetic and prove nothing
//     about meaning. The whole claim under test is "MiniLM puts the
//     motion loop near a request about transitions"; only MiniLM's own
//     numbers can support it.
//   - Calling the model inside the test would make the suite need a
//     network, a 23MB download and ~2s of load on every run, and would
//     make a CI failure ambiguous between a ranking regression and a
//     Hugging Face CDN outage.
//
// Recording it instead means the test is hermetic and fast, and the
// numbers are still real. The cost is that a model or text change makes
// vectors.json stale; hq.test.ts guards exactly that by re-deriving
// every key from the fixture store and failing if one is missing, and
// the live test re-derives the vectors from the model when it can run.

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { indexLoops } from './briefing'
import { loadMiniLM, MODEL_ID } from './embedding'
import { RECORDED_QUERIES, RECORDS } from './fixtures'
import { caseKey, caseText, queryText } from './semantic'

/** Six decimals. Cosine error from the truncation is ~1e-6, three orders
 *  below the four decimals SemanticReason rounds to, and it keeps the
 *  fixture diffable instead of a wall of 17-digit floats. */
const PRECISION = 6

export async function main(): Promise<number> {
  const embedder = await loadMiniLM()
  if (!embedder) {
    console.error('MiniLM could not be loaded. Install the optional dependency first:')
    console.error('  npm install --include=optional')
    return 1
  }

  const texts = new Map<string, string>()
  for (const indexed of indexLoops(RECORDS)) {
    texts.set(`case:${caseKey(indexed.recordId, indexed.loop.id)}`, caseText(indexed))
  }
  for (const q of RECORDED_QUERIES) texts.set(`query:${queryText(q.domain, q.files)}`, queryText(q.domain, q.files))

  const labels = [...texts.keys()]
  const vectors = await embedder.embed(labels.map((l) => texts.get(l)!))

  const out = {
    _comment:
      'Generated by src/hq/record-vectors.ts. Real all-MiniLM-L6-v2 output over the ' +
      'fixture store, recorded so the semantic ranking tests are hermetic. Regenerate ' +
      'with: npx tsx src/hq/record-vectors.ts',
    model: MODEL_ID,
    dims: embedder.dims,
    recordedAt: new Date().toISOString().slice(0, 10),
    texts: Object.fromEntries(labels.map((l) => [l, texts.get(l)!])),
    vectors: Object.fromEntries(
      labels.map((l, i) => [l, vectors[i].map((x) => Number(x.toFixed(PRECISION)))])
    ),
  }
  const path = join(import.meta.dirname, 'vectors.json')
  writeFileSync(path, `${JSON.stringify(out, null, 1)}\n`, 'utf8')
  console.log(`recorded ${labels.length} vectors (${embedder.dims}d) -> ${path}`)
  return 0
}

const invokedDirectly = process.argv[1]?.endsWith('record-vectors.ts')
// .then rather than top-level await: tsx transforms this file to CJS when it
// is imported from outside the package, and CJS has no top-level await.
if (invokedDirectly) void main().then((code) => process.exit(code))
